language: python
env:
  global:
  - JEKYLL_ENV=production
  - PLACE=za-wc012
  - secure: fGYZZz9FVeUpcBFTQfdELtmFMwnPoUHUJC2Y2vr/zP31axzgs5wEXD7x19qykXULzPt2+EK9gXaxYOvt/huJciK2Ui4HGDA8BgHbnfEeLA6YfFVPc7ZT3aL5gsVX4SmkIeJQX3UycqEfURYsSRsqKAINo6YC8GwbVDb6GGnK2/Lqks9tBhCuK8o0s0u1CDKu32GjfxykRkECb2gYdT7Cp7zJK1QN/p2us0ULe7bCeWJJLiF1YpBbn3RE2CbHcNGn0HBGrcMGDql0j4ZahEmush4ze2XxkP/WDIPYGD9EVH3PCTrdqXQmQBftu8xYZ24++9XWgC1ETC1ALtpp81zBs/n1czRBoXlyjrLb/B3MxAHPKBr5CJZZ+AvMhfqfVvMHKL0X58A+f4dhYAgvl2iPlhrE3SjCidzsDOzXa68OXKjxopBLykGchg+z3rcF6c09BGnS+okycfYpb9S4JjMhFOVxiJg1vQJOMDn6rckKsxX4XduOITJcdUA70jCu7bI3yI+oeozU3p5PrBEeSfMZsnMB4uzDC2a78JUM7WaPhhdpvAMASd7OSQf1M2KKofXq8nSXol08/AoLNpmW+zZba5XwSFi82ytqE+RNqusbo83HK+905ELc2F/HEc4cE8878HjzSR/X2SQbGUuYJzQspIIPztq+NPAGh7ysQoWXea8=
  - secure: rfVzZQFWDYfYd4JK5EQDfyNtq49X3aR+zehitFMC5YgfGg2d3YprPZZwZJH8ts8LkazV8X8OeK9PSwp31x/f9pz6WPGs89nCIlEVptg+sMQxycgHXxFFRAjQWrVOk0SgTzeXv8TbM/GRW9lhWeUTsZ4pPsLct6IL1IC2bcTqj0BQxVEsmpB1UoER6Srns/J1rE96xzxjCfwEdxH730YQFi+71r5okUtubETbwiYC5/r9LMvuEkkCq1nSB7w3nnuUur9cQHzjfJQxLOXyj+PepZH8+djd5TgVJIeHI0wARM9vMuihY9nBfqsf3TqQmgq1y6c9qLa4cWDrXPNB74F0+hShvHSLVyj8CEJm7ErOb0IEWwMwwsiGZVniyG5H+7TeaMDKXC8MVyDT/QF/QJWqiorCHd8S8mRQ0PrafIZb+CnppPYEyF2Tsraf/+SonIO8F0/gP4Z2p7MdFKT9GVhesvGRRhOlulki/3xHj1/BE4/JhE5gp8HprJe2WOy6OCoawrQnqHwh6u9W4hnyQozlytoITSaqC9PfKEBCUrEEUE+EQf3EijY2O1J0zZUWg2DOKtGGiCrHo2OKIp+7A8iwWCv1sxU1eQ3ODy9/PtRGLSZSXPb84Ri0pfi229yK5rNhaeTkt9/n1Lm5RzL22O3qlh13KnRKwxdecK/LOKUIwYU=
install:
- git clone --depth 1 https://github.com/laws-africa/openbylaws-microsite.git build
- cd build
- pip install -r requirements.txt
- bundle install
- python bin/place.py $PLACE
script: bundle exec jekyll build --trace
deploy:
  provider: pages
  local_dir: build/_site
  target_branch: gh-pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  fqdn: bergrivier.openbylaws.org.za
  on:
    branch: master
